services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather-app-backend
    ports:
      - "8000:8000"
    environment:
      # Weather API Configuration (required)
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_BASE_URL=https://api.weatherapi.com/v1
      - API_TIMEOUT=10
      
      # Application Configuration
      - APP_NAME=Weather App
      - APP_VERSION=1.0.0
      - DEBUG=false
      
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      
      # Cache Configuration
      - CACHE_TTL=300
    volumes:
      - ./backend:/app
    networks:
      - weather-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - weather-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  weather-network:
    driver: bridge
    name: weather-app-network

volumes:
  backend_data:
    name: weather-app-backend-data
